# Generated by Django 5.2.8 on 2025-11-15 08:48

from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ('report_builder', '0007_auto_20190214_1405'),  # Check your last migration number
    ]

    operations = [
        migrations.AddField(
            model_name='displayfield',
            name='order_by',
            field=models.CharField(
                max_length=4, 
                choices=[('asc', 'Ascending'), ('desc', 'Descending'), ('', 'No Order')], 
                blank=True, 
                default='',
                help_text='Sort order for this field'
            ),
        ),
    ]
